'use strict';
const $=id=>document.getElementById(id);
let slides=[],current=0;
function go(n){n=Math.max(1,Math.min(slides.length,Number(n)||1));if(location.hash===`#/${n}`)render();else location.hash=`/${n}`;}
function render(){const m=location.hash.match(/^#\/(\d+)/);current=Math.max(0,Math.min(slides.length-1,(m?Number(m[1]):1)-1));const s=slides[current];$('media').querySelectorAll('video').forEach(v=>v.pause());$('media').replaceChildren();$('slide').src=s.image;$('slide').alt=`Slide ${current+1}: ${s.text}`;$('page').value=current+1;$('prev').disabled=current===0;$('next').disabled=current===slides.length-1;$('section').textContent=current>=71?'Appendix':'Defense';document.title=`${current+1} · ${s.title} · Ziqing Guo`;$('status').textContent=`Slide ${current+1} of ${slides.length}: ${s.title}`;
for(const v of s.videos){const frame=document.createElement('div');frame.className='video-frame';Object.assign(frame.style,{left:v.x+'%',top:v.y+'%',width:v.w+'%',height:v.h+'%'});const video=document.createElement('video');video.src=v.src;video.poster=v.poster;video.preload='metadata';video.playsInline=true;video.loop=true;video.setAttribute('aria-label',`Slide ${current+1} video`);const c=v.crop,w=1-c.l-c.r,h=1-c.t-c.b;Object.assign(video.style,{width:100/w+'%',height:100/h+'%',left:-100*c.l/w+'%',top:-100*c.t/h+'%',objectFit:'fill'});const play=document.createElement('button');play.className='video-play';play.textContent='▶ Play video';const toggle=()=>{if(video.paused)video.play().catch(()=>{play.textContent='Retry video';});else video.pause();};play.onclick=toggle;video.onclick=toggle;video.onplay=()=>{frame.classList.add('playing');play.textContent='Ⅱ Pause video';};video.onpause=()=>{frame.classList.remove('playing');play.textContent='▶ Play video';};frame.append(video,play);$('media').append(frame);}
for(const n of [current-1,current+1])if(slides[n]){const img=new Image();img.src=slides[n].image;}
}
$('prev').onclick=()=>go(current);$('next').onclick=()=>go(current+2);$('page').onchange=e=>go(e.target.value);$('page').onkeydown=e=>{if(e.key==='Enter'){go(e.target.value);e.target.blur();}};
function full(){if(document.fullscreenElement)document.exitFullscreen();else if(document.documentElement.requestFullscreen)document.documentElement.requestFullscreen();}
$('fullscreen').onclick=full;
$('browse').onclick=()=>{$('grid').querySelectorAll('button').forEach((b,i)=>b.setAttribute('aria-current',i===current));$('overview').showModal();$('grid').children[current]?.scrollIntoView({block:'center'});};$('close').onclick=()=>$('overview').close();
window.addEventListener('hashchange',()=>{if(slides.length)render();});
window.addEventListener('keydown',e=>{if(!slides.length||$('overview').open||document.activeElement.tagName==='INPUT')return;if(e.key===' '&&['BUTTON','A'].includes(document.activeElement.tagName))return;if(['ArrowRight','ArrowDown','PageDown',' '].includes(e.key)){e.preventDefault();go(current+2);}if(['ArrowLeft','ArrowUp','PageUp'].includes(e.key)){e.preventDefault();go(current);}if(e.key==='Home')go(1);if(e.key==='End')go(slides.length);if(e.key.toLowerCase()==='f')full();});
let touchX=0,touchY=0;$('viewer').addEventListener('touchstart',e=>{touchX=e.changedTouches[0].clientX;touchY=e.changedTouches[0].clientY;},{passive:true});$('viewer').addEventListener('touchend',e=>{if(e.target.closest('.video-frame'))return;const dx=e.changedTouches[0].clientX-touchX,dy=e.changedTouches[0].clientY-touchY;if(Math.abs(dx)>60&&Math.abs(dx)>Math.abs(dy)*1.5)go(current+(dx<0?2:0));},{passive:true});
fetch('slides.json').then(r=>{if(!r.ok)throw Error('slides');return r.json();}).then(data=>{slides=data;$('page').max=slides.length;for(let i=0;i<slides.length;i++){const b=document.createElement('button'),im=document.createElement('img'),label=document.createElement('span');im.src=slides[i].thumb;im.alt='';im.loading='lazy';label.textContent=`${i+1}. ${slides[i].title}`;b.append(im,label);b.onclick=()=>{go(i+1);$('overview').close();$('browse').blur();};$('grid').append(b);}render();}).catch(()=>{$('status').className='';$('status').textContent='The slides could not load. Please refresh, or use the PDF or PowerPoint links.';});
